//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskSchedule
    {
        public int ID_taskSchedule { get; set; }
        public int ID_taskSubdivision { get; set; }
        public int ID_employee { get; set; }
        public System.DateTime Date { get; set; }
        public string Comment { get; set; }
        public Nullable<int> SpentTime { get; set; }
        public string Description { get; set; }
        public int ID_status { get; set; }
        public Nullable<int> ID_prioritet { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<int> ID_task { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Prioritet Prioritet { get; set; }
        public virtual Status Status { get; set; }
        public virtual Tasks Tasks { get; set; }
        public virtual TaskSubdivision TaskSubdivision { get; set; }
    }
}
