//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskSubdivision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskSubdivision()
        {
            this.TaskSchedule = new HashSet<TaskSchedule>();
        }
    
        public int ID_taskSubdivision { get; set; }
        public string Description { get; set; }
        public Nullable<int> SpentTime { get; set; }
        public System.DateTime Date { get; set; }
        public int ID_status { get; set; }
        public int ID_subdivision { get; set; }
        public int ID_task { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Subdivision Subdivision { get; set; }
        public virtual Tasks Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskSchedule> TaskSchedule { get; set; }
    }
}
